"""Pushing changes

Revision ID: 06086989da5d
Revises: efa53df589bd
Create Date: 2025-01-27 09:11:54.911074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '06086989da5d'
down_revision: Union[str, None] = 'efa53df589bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('component_html', sa.Text(), nullable=True))
    op.add_column('chat', sa.Column('component_ft', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'component_ft')
    op.drop_column('chat', 'component_html')
    # ### end Alembic commands ###
