"""Pushing changes

Revision ID: 2e419b2e70c0
Revises: f8bdf6269442
Create Date: 2025-01-27 10:28:05.312849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e419b2e70c0'
down_revision: Union[str, None] = 'f8bdf6269442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessage', sa.Column('component_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatmessage', 'component_html')
    # ### end Alembic commands ###
