"""Pushing changes

Revision ID: cfaf7512d0c2
Revises: 2e419b2e70c0
Create Date: 2025-02-09 11:48:10.250392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cfaf7512d0c2'
down_revision: Union[str, None] = '2e419b2e70c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessage', sa.Column('component_ft', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatmessage', 'component_ft')
    # ### end Alembic commands ###
