"""Pushing changes

Revision ID: f8bdf6269442
Revises: 06086989da5d
Create Date: 2025-01-27 10:04:31.717409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f8bdf6269442'
down_revision: Union[str, None] = '06086989da5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatmessage', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessage', sa.Column('timestamp', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
